language: python
python:
  - "3.9"
# command to run tests

install:
    - pip install pandas
    - pip install requests
    - pip install plotly
    - pip install altair


script:
  - python ./test/TestExtract.py
  - python ./test/TestProcess.py
  - python ./test/TestViz.py
