language: python
python:
  - "3.9"
# command to run tests

install:
    - pip install pandas
    - pip install requests
    

script:
  - python ./test/TestExtract.py
  - python ./test/TestProcess.py
